version: "2.2"
services:
    schema-registry:
        container_name: schema-registry
        image: confluentinc/cp-schema-registry:5.5.0
        restart: always
        volumes:
          - ./config:/tmp/conf
        ports:
          - "8081:8081"
        network_mode: host
        environment:
          - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=localhost:9092
          - SCHEMA_REGISTRY_KAFKASTORE_TOPIC=_schemas
          - SCHEMA_REGISTRY_HOST_NAME=schema-registry
          - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
          - SCHEMA_REGISTRY_DEBUG=true
        ulimits:
          nproc: 65535
          nofile:
            soft: 65535
            hard: 65535
        logging:
            driver: json-file
            options:
              max-size: "100m"
              max-file: "3"
